In [27]:
import numpy as np
import notebooks.latex_utils as latex

def vector_norm_2(vector: np.ndarray):
    return np.sqrt(np.sum(np.array([ x**2 for x in vector ])))

def vector_norm_inf(vector: np.ndarray):
    return np.max([ abs(x) for x in vector])

def matrix_norm(A: np.ndarray):
    return np.max([ abs(x) for x in A])

rnd = np.random.RandomState(2)

#{{3.0, -2, 1, 4},{-2, -6, 2, -1},{1, 2, -2, 5},{4, -1, 5, -7}}
A: np.ndarray = np.array([
    [3.0, -2, 1, 4],
    [-2, -6, 2, -1],
    [1, 2, -2, 5],
    [4, -1, 5, -7]
])
X: np.ndarray = np.array([1.0, 1, -1, -1]).T

N = 100
A = np.array( [ np.floor(rnd.random(N) * 20) - 10 for _ in range(0, N) ] )
X = (np.floor(rnd.random(N) * 20) - 10).T

A = np.array([
    [ 5.0, 4, 1, 1],
    [ 4, 5, 1, 1 ],
    [ 1, 1, 4, 2 ],
    [ 1, 1, 2, 4 ]
])
# { {  5.0, 4, 1, 1 }, { 4, 5, 1, 1 }, { 1, 1, 4, 2 }, { 1, 1, 2, 4 } }
X: np.ndarray = np.array([-1.0, -1, 1, 1]).T

def power_method(A: np.ndarray, X: np.ndarray, aitken: bool = True):
    err = 1.0
    k = 1
    prevR = None
    prev2R = None
    W = X
    r = 0.0
    while err > 0.0000001 and k < 5000:
        norm = vector_norm_inf(X)
        W = X / norm
        r = W.T @ X
        if aitken and prev2R is not None:
            dr = prevR - prev2R
            dr2 = r - 2 * prevR + prev2R
            r = r - dr * dr / dr2
        X = A @ W
        print(X)
        print(f"Step: {k}: err = {err:.7f}, r= {r:.7f}")
        if prevR is not None:
            err = abs(r - prevR)
        k = k + 1
        prev2R = prevR
        prevR = r

    # print(f"Steps: {k}: err = {err:.7f}, r= {r:.7f}")
    return r, np.array([W]).T


def check(A: np.ndarray, eigValue: np.ndarray, eigVector: np.ndarray):
    v = eigVector.copy()
    p = 100
    print(vector_norm_inf(v))
    print(vector_norm_2(v))
    for i in range(0, p):
        print(v.T)
        v = A @ v / eigValue# / 0.4

    latex.print_latex(r"\lambda=" + str(np.round(eigValue, 6)) + r", v_\lambda = " + latex.matrix(np.round(eigVector, 6)) + r"\approx v_\lambda^{" + str(p) + "}" + latex.matrix(np.round(v, 6)))

def shift_matrix(A: np.ndarray, shift: float):
    n = X.size
    return A - np.diag([shift for _ in range(n)])


shifts = [ 0., 3., 6., 11.]
# shifts = [ 0. ]
# A= A/matrix_norm(A)
for shift in shifts:
    As: np.ndarray = shift_matrix(A, shift)
    eigValue, eigVector = power_method(As, X, False)
    latex.print_latex(r"||A-\mu I||_\infty=" + str(matrix_norm(As)) + r", \mu=" + str(shift))
    check(A, eigValue, eigVector)

# latex.print_latex("A = " + latex.matrix(A))
# latex.print_latex(f"\lambda = {eigValue}")


[-7. -7.  4.  4.]
Step: 1: err = 1.0000000, r= 4.0000000
[-7.85714286 -7.85714286  1.42857143  1.42857143]
Step: 2: err = 1.0000000, r= 18.5714286
[-8.63636364 -8.63636364 -0.90909091 -0.90909091]
Step: 3: err = 14.5714286, r= 16.2337662
[-9.21052632 -9.21052632 -2.63157895 -2.63157895]
Step: 4: err = 2.3376623, r= 17.4641148
[-9.57142857 -9.57142857 -3.71428571 -3.71428571]
Step: 5: err = 1.2303486, r= 19.9248120
[-9.7761194  -9.7761194  -4.32835821 -4.32835821]
Step: 6: err = 2.4606972, r= 22.0255864
[-9.88549618 -9.88549618 -4.65648855 -4.65648855]
Step: 7: err = 2.1007743, r= 23.3849835
[-9.94208494 -9.94208494 -4.82625483 -4.82625483]
Step: 8: err = 1.3593971, r= 24.1578001
[-9.97087379 -9.97087379 -4.91262136 -4.91262136]
Step: 9: err = 0.7728166, r= 24.5698542
[-9.98539435 -9.98539435 -4.95618306 -4.95618306]
Step: 10: err = 0.4120541, r= 24.7826169
[-9.99268649 -9.99268649 -4.97805948 -4.97805948]
Step: 11: err = 0.2127627, r= 24.8907247
[-9.99634057 -9.99634057 -4.98902171 -4.

$$\begin{align}||A-\mu I||_\infty=5.0, \mu=0.0\end{align}$$

1.0
1.581138828979777
[[-1.  -1.  -0.5 -0.5]]
[[-0.4 -0.4 -0.2 -0.2]]
[[-0.16 -0.16 -0.08 -0.08]]
[[-0.064 -0.064 -0.032 -0.032]]
[[-0.0256 -0.0256 -0.0128 -0.0128]]
[[-0.01024 -0.01024 -0.00512 -0.00512]]
[[-0.004096 -0.004096 -0.002048 -0.002048]]
[[-0.0016384 -0.0016384 -0.0008192 -0.0008192]]
[[-0.00065536 -0.00065536 -0.00032768 -0.00032768]]
[[-0.00026214 -0.00026214 -0.00013107 -0.00013107]]
[[-1.04857602e-04 -1.04857602e-04 -5.24288011e-05 -5.24288011e-05]]
[[-4.19430409e-05 -4.19430409e-05 -2.09715205e-05 -2.09715205e-05]]
[[-1.67772164e-05 -1.67772164e-05 -8.38860821e-06 -8.38860821e-06]]
[[-6.71088658e-06 -6.71088658e-06 -3.35544329e-06 -3.35544329e-06]]
[[-2.68435464e-06 -2.68435464e-06 -1.34217732e-06 -1.34217732e-06]]
[[-1.07374186e-06 -1.07374186e-06 -5.36870928e-07 -5.36870928e-07]]
[[-4.29496744e-07 -4.29496744e-07 -2.14748372e-07 -2.14748372e-07]]
[[-1.71798698e-07 -1.71798698e-07 -8.58993489e-08 -8.58993489e-08]]
[[-6.87194793e-08 -6.87194793e-08 -3.43597396e-08 -3.4

$$\begin{align}\lambda=25.0, v_\lambda = \begin{bmatrix}-1.0\\-1.0\\-0.5\\-0.5\\\end{bmatrix}\approx v_\lambda^{100}\begin{bmatrix}-0.0\\-0.0\\-0.0\\-0.0\\\end{bmatrix}\end{align}$$

[-4. -4.  1.  1.]
Step: 1: err = 1.0000000, r= 4.0000000
[-5.5  -5.5  -1.25 -1.25]
Step: 2: err = 1.0000000, r= 8.5000000
[-6.45454545 -6.45454545 -2.68181818 -2.68181818]
Step: 3: err = 4.5000000, r= 11.5681818
[-6.83098592 -6.83098592 -3.24647887 -3.24647887]
Step: 4: err = 3.0681818, r= 15.1376440
[-6.95051546 -6.95051546 -3.4257732  -3.4257732 ]
Step: 5: err = 3.5694622, r= 16.7478002
[-6.9857609  -6.9857609  -3.47864135 -3.47864135]
Step: 6: err = 1.6101562, r= 17.2780242
[-6.99592339 -6.99592339 -3.49388509 -3.49388509]
Step: 7: err = 0.5302240, r= 17.4359821
[-6.99883458 -6.99883458 -3.49825186 -3.49825186]
Step: 8: err = 0.1579579, r= 17.4816600
[-6.99966697 -6.99966697 -3.49950045 -3.49950045]
Step: 9: err = 0.0456779, r= 17.4947560
[-6.99990484 -6.99990484 -3.49985726 -3.49985726]
Step: 10: err = 0.0130960, r= 17.4985014
[-6.99997281 -6.99997281 -3.49995922 -3.49995922]
Step: 11: err = 0.0037454, r= 17.4995718
[-6.99999223 -6.99999223 -3.49998835 -3.49998835]
Step: 12: err = 

$$\begin{align}||A-\mu I||_\infty=4.0, \mu=3.0\end{align}$$

1.0
1.581138829702389
[[-1.  -1.  -0.5 -0.5]]
[[-0.57142857 -0.57142857 -0.28571429 -0.28571429]]
[[-0.32653061 -0.32653061 -0.16326531 -0.16326531]]
[[-0.18658892 -0.18658892 -0.09329446 -0.09329446]]
[[-0.10662224 -0.10662224 -0.05331112 -0.05331112]]
[[-0.060927  -0.060927  -0.0304635 -0.0304635]]
[[-0.03481543 -0.03481543 -0.01740771 -0.01740771]]
[[-0.01989453 -0.01989453 -0.00994726 -0.00994726]]
[[-0.0113683  -0.0113683  -0.00568415 -0.00568415]]
[[-0.00649617 -0.00649617 -0.00324809 -0.00324809]]
[[-0.0037121  -0.0037121  -0.00185605 -0.00185605]]
[[-0.0021212 -0.0021212 -0.0010606 -0.0010606]]
[[-0.00121211 -0.00121211 -0.00060606 -0.00060606]]
[[-0.00069264 -0.00069264 -0.00034632 -0.00034632]]
[[-0.00039579 -0.00039579 -0.0001979  -0.0001979 ]]
[[-0.00022617 -0.00022617 -0.00011308 -0.00011308]]
[[-1.29238298e-04 -1.29238298e-04 -6.46191488e-05 -6.46191488e-05]]
[[-7.38504558e-05 -7.38504558e-05 -3.69252279e-05 -3.69252279e-05]]
[[-4.22002605e-05 -4.22002605e-05 -2.11001303e

$$\begin{align}\lambda=17.5, v_\lambda = \begin{bmatrix}-1.0\\-1.0\\-0.5\\-0.5\\\end{bmatrix}\approx v_\lambda^{100}\begin{bmatrix}-0.0\\-0.0\\-0.0\\-0.0\\\end{bmatrix}\end{align}$$

[-1. -1. -2. -2.]
Step: 1: err = 1.0000000, r= 4.0000000
[-3.5 -3.5 -1.  -1. ]
Step: 2: err = 1.0000000, r= 5.0000000
[-3.57142857 -3.57142857 -2.         -2.        ]
Step: 3: err = 1.0000000, r= 7.5714286
[-4.12 -4.12 -2.   -2.  ]
Step: 4: err = 2.5714286, r= 9.3828571
[-3.97087379 -3.97087379 -2.         -2.        ]
Step: 5: err = 1.8114286, r= 10.1817476
[-4.00733496 -4.00733496 -2.         -2.        ]
Step: 6: err = 0.7988904, r= 9.9564175
[-3.99816962 -3.99816962 -2.         -2.        ]
Step: 7: err = 0.2253301, r= 10.0110092
[-4.00045781 -4.00045781 -2.         -2.        ]
Step: 8: err = 0.0545917, r= 9.9972548
[-3.99988556 -3.99988556 -2.         -2.        ]
Step: 9: err = 0.0137543, r= 10.0006867
[-4.00002861 -4.00002861 -2.         -2.        ]
Step: 10: err = 0.0034319, r= 9.9998283
[-3.99999285 -3.99999285 -2.         -2.        ]
Step: 11: err = 0.0008584, r= 10.0000429
[-4.00000179 -4.00000179 -2.         -2.        ]
Step: 12: err = 0.0002146, r= 9.9999893
[-3.99999

$$\begin{align}||A-\mu I||_\infty=4.0, \mu=6.0\end{align}$$

1.0
1.5811388295319833
[[-1.  -1.  -0.5 -0.5]]
[[-1.  -1.  -0.5 -0.5]]
[[-1.  -1.  -0.5 -0.5]]
[[-1.  -1.  -0.5 -0.5]]
[[-1.  -1.  -0.5 -0.5]]
[[-0.99999999 -0.99999999 -0.5        -0.5       ]]
[[-0.99999999 -0.99999999 -0.5        -0.5       ]]
[[-0.99999999 -0.99999999 -0.5        -0.5       ]]
[[-0.99999999 -0.99999999 -0.5        -0.5       ]]
[[-0.99999999 -0.99999999 -0.5        -0.5       ]]
[[-0.99999999 -0.99999999 -0.49999999 -0.49999999]]
[[-0.99999999 -0.99999999 -0.49999999 -0.49999999]]
[[-0.99999999 -0.99999999 -0.49999999 -0.49999999]]
[[-0.99999999 -0.99999999 -0.49999999 -0.49999999]]
[[-0.99999998 -0.99999998 -0.49999999 -0.49999999]]
[[-0.99999998 -0.99999998 -0.49999999 -0.49999999]]
[[-0.99999998 -0.99999998 -0.49999999 -0.49999999]]
[[-0.99999998 -0.99999998 -0.49999999 -0.49999999]]
[[-0.99999998 -0.99999998 -0.49999999 -0.49999999]]
[[-0.99999998 -0.99999998 -0.49999999 -0.49999999]]
[[-0.99999998 -0.99999998 -0.49999999 -0.49999999]]
[[-0.99999998 -0.99999998

$$\begin{align}\lambda=10.0, v_\lambda = \begin{bmatrix}-1.0\\-1.0\\-0.5\\-0.5\\\end{bmatrix}\approx v_\lambda^{100}\begin{bmatrix}-1.0\\-1.0\\-0.5\\-0.5\\\end{bmatrix}\end{align}$$

[ 4.  4. -7. -7.]
Step: 1: err = 1.0000000, r= 4.0000000
[-3.14285714 -3.14285714  6.14285714  6.14285714]
Step: 2: err = 1.0000000, r= 18.5714286
[ 3.02325581  3.02325581 -6.02325581 -6.02325581]
Step: 3: err = 14.5714286, r= 15.5016611
[-3.003861 -3.003861  6.003861  6.003861]
Step: 4: err = 3.0697674, r= 15.0814402
[ 3.00064309  3.00064309 -6.00064309 -6.00064309]
Step: 5: err = 0.4202209, r= 15.0135148
[-3.00010717 -3.00010717  6.00010717  6.00010717]
Step: 6: err = 0.0679255, r= 15.0022508
[ 3.00001786  3.00001786 -6.00001786 -6.00001786]
Step: 7: err = 0.0112639, r= 15.0003751
[-3.00000298 -3.00000298  6.00000298  6.00000298]
Step: 8: err = 0.0018757, r= 15.0000625
[ 3.0000005  3.0000005 -6.0000005 -6.0000005]
Step: 9: err = 0.0003126, r= 15.0000104
[-3.00000008 -3.00000008  6.00000008  6.00000008]
Step: 10: err = 0.0000521, r= 15.0000017
[ 3.00000001  3.00000001 -6.00000001 -6.00000001]
Step: 11: err = 0.0000087, r= 15.0000003
[-3. -3.  6.  6.]
Step: 12: err = 0.0000014, r= 15.0

$$\begin{align}||A-\mu I||_\infty=7.0, \mu=11.0\end{align}$$

1.0
1.5811388302052505
[[-0.5 -0.5  1.   1. ]]
[[-0.16666667 -0.16666667  0.33333333  0.33333333]]
[[-0.05555556 -0.05555556  0.11111111  0.11111111]]
[[-0.01851852 -0.01851852  0.03703704  0.03703704]]
[[-0.00617284 -0.00617284  0.01234568  0.01234568]]
[[-0.00205761 -0.00205761  0.00411523  0.00411523]]
[[-0.00068587 -0.00068587  0.00137174  0.00137174]]
[[-0.00022862 -0.00022862  0.00045725  0.00045725]]
[[-7.62079008e-05 -7.62079008e-05  1.52415787e-04  1.52415787e-04]]
[[-2.54026356e-05 -2.54026356e-05  5.08052612e-05  5.08052612e-05]]
[[-8.46754652e-06 -8.46754652e-06  1.69350864e-05  1.69350864e-05]]
[[-2.82251639e-06 -2.82251639e-06  5.64502835e-06  5.64502835e-06]]
[[-9.40839386e-07 -9.40839386e-07  1.88167582e-06  1.88167582e-06]]
[[-3.13613522e-07 -3.13613522e-07  6.27225077e-07  6.27225077e-07]]
[[-1.04538103e-07 -1.04538103e-07  2.09074894e-07  2.09074894e-07]]
[[-3.48462091e-08 -3.48462091e-08  6.96915440e-08  6.96915440e-08]]
[[-1.16155196e-08 -1.16155196e-08  2.32304564

$$\begin{align}\lambda=15.0, v_\lambda = \begin{bmatrix}-0.5\\-0.5\\1.0\\1.0\\\end{bmatrix}\approx v_\lambda^{100}\begin{bmatrix}-0.0\\-0.0\\-0.0\\-0.0\\\end{bmatrix}\end{align}$$