In [1]:
import numpy as np

def multiply(A, B):
    n, m = np.shape(A)
    m1, k = np.shape(B)
    if m1 != m:
        raise ValueError("Incompatible matrix size. Must be m, n and n, k")
    C = np.ndarray(shape = (n, k))
    for i in range(0, n):
        for j in range(0, k):
            s = 0
            for a in range(0, m):
                s = s + A[i][a] * B[a][j]
            C[i][j] = s
    return C

def dot(x, y):
    n = np.size(x)
    if np.shape(x) != np.shape(y):
        raise ValueError("Vectors must be of the same size.")
    return sum([ x[i] * y[i] for i in range(0,n)])

A = [
    [1,2],
    [3,0],
    [-1,4]
]
B = [
    [1, 0, 2],
    [3, 1, 1]
]
print(multiply(A, B))

x = [1,2,0]
y=[3,4,1]
print(dot(x, y))


[[ 7.  2.  4.]
 [ 3.  0.  6.]
 [11.  4.  2.]]
11
